Models/MonAn.cs
namespace SmartCookFinal.Models
{
	public class MonAn
	{
        public int Id { get; set; }
        public string? TenMon { get; set; }
        public string? MoTa { get; set; }
        public string? LoaiBuaAn { get; set; }
        public int? ThoiGianNau { get; set; }
        public int? LuongCalo { get; set; }
		public double? Carbs { get; set; }
		public double? Protein { get; set; }
		public double? Fat { get; set; }
		public decimal? ChiPhiUocTinh { get; set; }
        public bool? Chay { get; set; }
        public bool? AnKeto { get; set; }
        public bool? AnKhongGluten { get; set; }
        public string? NguyenLieuChinh { get; set; }
        public string? DinhDuongChiTiet { get; set; }
        public string? UrlHinhAnh { get; set; }
        public string? CachNau { get; set; }
        public bool? TrangThai { get; set; }

        public int? DanhMucId { get; set; }
		public DanhMucMonAn DanhMuc { get; set; }

		public ICollection<MonAnNguyenLieu> MonAnNguyenLieus { get; set; }
		public ICollection<ThucDonChiTiet> ThucDonChiTiets { get; set; }
	}

}

Controllers/MonAnsController.cs
using System;
using System.Collections.Generic;
using System.Linq;
using System.Threading.Tasks;
using Microsoft.AspNetCore.Mvc;
using Microsoft.AspNetCore.Mvc.Rendering;
using Microsoft.EntityFrameworkCore;
using SmartCookFinal.Models;
using X.PagedList.EntityFramework;
using X.PagedList.Extensions;
using X.PagedList;

namespace SmartCookFinal.Controllers
{
    public class MonAnsController : Controller
    {
        private readonly SmartCookContext _context;

        public MonAnsController(SmartCookContext context)
        {
            _context = context;
        }

		// GET: MonAns
		public IActionResult Index(int? page)
		{
			int pageSize = 12;
			int pageNumber = page ?? 1;

			var monAnList = _context.MonAns.Include(m => m.DanhMuc).OrderBy(m => m.Id);
            ViewBag.CurrentAction = "Index";

            return View(monAnList.ToPagedList(pageNumber, pageSize));
		}


		// GET: MonAns/Details/5
		public async Task<IActionResult> Details(int? id)
        {
            if (id == null)
            {
                return NotFound();
            }

            var monAn = await _context.MonAns
                .Include(m => m.DanhMuc)
                .FirstOrDefaultAsync(m => m.Id == id);
            if (monAn == null)
            {
                return NotFound();
            }

            return View(monAn);
        }

        // GET: MonAns/Create
        public IActionResult Create()
        {
            ViewData["DanhMucId"] = new SelectList(_context.DanhMucMonAns, "Id", "Id");
            return View();
        }

        // POST: MonAns/Create
        // To protect from overposting attacks, enable the specific properties you want to bind to.
        // For more details, see http://go.microsoft.com/fwlink/?LinkId=317598.
        [HttpPost]
        [ValidateAntiForgeryToken]
        public async Task<IActionResult> Create([Bind("Id,TenMon,MoTa,LoaiBuaAn,ThoiGianNau,LuongCalo,Carbs,Protein,Fat,ChiPhiUocTinh,Chay,AnKeto,AnKhongGluten,NguyenLieuChinh,DinhDuongChiTiet,UrlHinhAnh,CachNau,TrangThai,DanhMucId")] MonAn monAn)
        {
            if (ModelState.IsValid)
            {
                _context.Add(monAn);
                await _context.SaveChangesAsync();
                return RedirectToAction(nameof(Index));
            }
            ViewData["DanhMucId"] = new SelectList(_context.DanhMucMonAns, "Id", "Id", monAn.DanhMucId);
            return View(monAn);
        }

        // GET: MonAns/Edit/5
        public async Task<IActionResult> Edit(int? id)
        {
            if (id == null)
            {
                return NotFound();
            }

            var monAn = await _context.MonAns.FindAsync(id);
            if (monAn == null)
            {
                return NotFound();
            }
            ViewData["DanhMucId"] = new SelectList(_context.DanhMucMonAns, "Id", "Id", monAn.DanhMucId);
            return View(monAn);
        }

        // POST: MonAns/Edit/5
        // To protect from overposting attacks, enable the specific properties you want to bind to.
        // For more details, see http://go.microsoft.com/fwlink/?LinkId=317598.
        [HttpPost]
        [ValidateAntiForgeryToken]
        public async Task<IActionResult> Edit(int id, [Bind("Id,TenMon,MoTa,LoaiBuaAn,ThoiGianNau,LuongCalo,Carbs,Protein,Fat,ChiPhiUocTinh,Chay,AnKeto,AnKhongGluten,NguyenLieuChinh,DinhDuongChiTiet,UrlHinhAnh,CachNau,TrangThai,DanhMucId")] MonAn monAn)
        {
            if (id != monAn.Id)
            {
                return NotFound();
            }

            if (ModelState.IsValid)
            {
                try
                {
                    _context.Update(monAn);
                    await _context.SaveChangesAsync();
                }
                catch (DbUpdateConcurrencyException)
                {
                    if (!MonAnExists(monAn.Id))
                    {
                        return NotFound();
                    }
                    else
                    {
                        throw;
                    }
                }
                return RedirectToAction(nameof(Index));
            }
            ViewData["DanhMucId"] = new SelectList(_context.DanhMucMonAns, "Id", "Id", monAn.DanhMucId);
            return View(monAn);
        }

        // GET: MonAns/Delete/5
        public async Task<IActionResult> Delete(int? id)
        {
            if (id == null)
            {
                return NotFound();
            }

            var monAn = await _context.MonAns
                .Include(m => m.DanhMuc)
                .FirstOrDefaultAsync(m => m.Id == id);
            if (monAn == null)
            {
                return NotFound();
            }

            return View(monAn);
        }

        // POST: MonAns/Delete/5
        [HttpPost, ActionName("Delete")]
        [ValidateAntiForgeryToken]
        public async Task<IActionResult> DeleteConfirmed(int id)
        {
            var monAn = await _context.MonAns.FindAsync(id);
            if (monAn != null)
            {
                _context.MonAns.Remove(monAn);
            }

            await _context.SaveChangesAsync();
            return RedirectToAction(nameof(Index));
        }

        private bool MonAnExists(int id)
        {
            return _context.MonAns.Any(e => e.Id == id);
        }

		public async Task<IActionResult> SearchByName(string name, int? page)
		{
			int pageSize = 6;
			int pageNumber = page ?? 1;

			var query = _context.MonAns
				.Where(m => m.TenMon.Contains(name))
				.OrderBy(m => m.TenMon);

            ViewBag.SearchTerm = name;
            ViewBag.CurrentAction = "SearchByName";

            return View("Index", query.ToPagedList(pageNumber, pageSize));

        }

        public async Task<IActionResult> FilterByBuaAn(string loaiBuaAn, int? page)
		{
			int pageSize = 6;
			int pageNumber = page ?? 1;

			var query = _context.MonAns
				.Where(m => m.LoaiBuaAn != null && m.LoaiBuaAn.ToLower() == loaiBuaAn.ToLower())
				.OrderBy(m => m.TenMon);

            ViewBag.LoaiBuaAn = loaiBuaAn;
            ViewBag.CurrentAction = "FilterByBuaAn";

            return View("Index", query.ToPagedList(pageNumber, pageSize));

        }


    }
}

Views/MonAns/Create.cshtml
@model SmartCookFinal.Models.MonAn

@{
    ViewData["Title"] = "Create";
}

<h1>Create</h1>

<h4>MonAn</h4>
<hr />
<div class="row">
    <div class="col-md-4">
        <form asp-action="Create">
            <div asp-validation-summary="ModelOnly" class="text-danger"></div>
            <div class="form-group">
                <label asp-for="TenMon" class="control-label"></label>
                <input asp-for="TenMon" class="form-control" />
                <span asp-validation-for="TenMon" class="text-danger"></span>
            </div>
            <div class="form-group">
                <label asp-for="MoTa" class="control-label"></label>
                <input asp-for="MoTa" class="form-control" />
                <span asp-validation-for="MoTa" class="text-danger"></span>
            </div>
            <div class="form-group">
                <label asp-for="LoaiBuaAn" class="control-label"></label>
                <input asp-for="LoaiBuaAn" class="form-control" />
                <span asp-validation-for="LoaiBuaAn" class="text-danger"></span>
            </div>
            <div class="form-group">
                <label asp-for="ThoiGianNau" class="control-label"></label>
                <input asp-for="ThoiGianNau" class="form-control" />
                <span asp-validation-for="ThoiGianNau" class="text-danger"></span>
            </div>
            <div class="form-group">
                <label asp-for="LuongCalo" class="control-label"></label>
                <input asp-for="LuongCalo" class="form-control" />
                <span asp-validation-for="LuongCalo" class="text-danger"></span>
            </div>
            <div class="form-group">
                <label asp-for="Carbs" class="control-label"></label>
                <input asp-for="Carbs" class="form-control" />
                <span asp-validation-for="Carbs" class="text-danger"></span>
            </div>
            <div class="form-group">
                <label asp-for="Protein" class="control-label"></label>
                <input asp-for="Protein" class="form-control" />
                <span asp-validation-for="Protein" class="text-danger"></span>
            </div>
            <div class="form-group">
                <label asp-for="Fat" class="control-label"></label>
                <input asp-for="Fat" class="form-control" />
                <span asp-validation-for="Fat" class="text-danger"></span>
            </div>
            <div class="form-group">
                <label asp-for="ChiPhiUocTinh" class="control-label"></label>
                <input asp-for="ChiPhiUocTinh" class="form-control" />
                <span asp-validation-for="ChiPhiUocTinh" class="text-danger"></span>
            </div>
            <div class="form-group">
                <label asp-for="Chay" class="control-label"></label>
                <input asp-for="Chay" class="form-control" />
                <span asp-validation-for="Chay" class="text-danger"></span>
            </div>
            <div class="form-group">
                <label asp-for="AnKeto" class="control-label"></label>
                <input asp-for="AnKeto" class="form-control" />
                <span asp-validation-for="AnKeto" class="text-danger"></span>
            </div>
            <div class="form-group">
                <label asp-for="AnKhongGluten" class="control-label"></label>
                <input asp-for="AnKhongGluten" class="form-control" />
                <span asp-validation-for="AnKhongGluten" class="text-danger"></span>
            </div>
            <div class="form-group">
                <label asp-for="NguyenLieuChinh" class="control-label"></label>
                <input asp-for="NguyenLieuChinh" class="form-control" />
                <span asp-validation-for="NguyenLieuChinh" class="text-danger"></span>
            </div>
            <div class="form-group">
                <label asp-for="DinhDuongChiTiet" class="control-label"></label>
                <input asp-for="DinhDuongChiTiet" class="form-control" />
                <span asp-validation-for="DinhDuongChiTiet" class="text-danger"></span>
            </div>
            <div class="form-group">
                <label asp-for="UrlHinhAnh" class="control-label"></label>
                <input asp-for="UrlHinhAnh" class="form-control" />
                <span asp-validation-for="UrlHinhAnh" class="text-danger"></span>
            </div>
            <div class="form-group">
                <label asp-for="CachNau" class="control-label"></label>
                <input asp-for="CachNau" class="form-control" />
                <span asp-validation-for="CachNau" class="text-danger"></span>
            </div>
            <div class="form-group">
                <label asp-for="TrangThai" class="control-label"></label>
                <input asp-for="TrangThai" class="form-control" />
                <span asp-validation-for="TrangThai" class="text-danger"></span>
            </div>
            <div class="form-group">
                <label asp-for="DanhMucId" class="control-label"></label>
                <select asp-for="DanhMucId" class ="form-control" asp-items="ViewBag.DanhMucId"></select>
            </div>
            <div class="form-group">
                <input type="submit" value="Create" class="btn btn-primary" />
            </div>
        </form>
    </div>
</div>

<div>
    <a asp-action="Index">Back to List</a>
</div>

@section Scripts {
    @{await Html.RenderPartialAsync("_ValidationScriptsPartial");}
}

Views/MonAns/Delete.cshtml
@model SmartCookFinal.Models.MonAn

@{
    ViewData["Title"] = "Delete";
}

<h1>Delete</h1>

<h3>Are you sure you want to delete this?</h3>
<div>
    <h4>MonAn</h4>
    <hr />
    <dl class="row">
        <dt class = "col-sm-2">
            @Html.DisplayNameFor(model => model.TenMon)
        </dt>
        <dd class = "col-sm-10">
            @Html.DisplayFor(model => model.TenMon)
        </dd>
        <dt class = "col-sm-2">
            @Html.DisplayNameFor(model => model.MoTa)
        </dt>
        <dd class = "col-sm-10">
            @Html.DisplayFor(model => model.MoTa)
        </dd>
        <dt class = "col-sm-2">
            @Html.DisplayNameFor(model => model.LoaiBuaAn)
        </dt>
        <dd class = "col-sm-10">
            @Html.DisplayFor(model => model.LoaiBuaAn)
        </dd>
        <dt class = "col-sm-2">
            @Html.DisplayNameFor(model => model.ThoiGianNau)
        </dt>
        <dd class = "col-sm-10">
            @Html.DisplayFor(model => model.ThoiGianNau)
        </dd>
        <dt class = "col-sm-2">
            @Html.DisplayNameFor(model => model.LuongCalo)
        </dt>
        <dd class = "col-sm-10">
            @Html.DisplayFor(model => model.LuongCalo)
        </dd>
        <dt class = "col-sm-2">
            @Html.DisplayNameFor(model => model.Carbs)
        </dt>
        <dd class = "col-sm-10">
            @Html.DisplayFor(model => model.Carbs)
        </dd>
        <dt class = "col-sm-2">
            @Html.DisplayNameFor(model => model.Protein)
        </dt>
        <dd class = "col-sm-10">
            @Html.DisplayFor(model => model.Protein)
        </dd>
        <dt class = "col-sm-2">
            @Html.DisplayNameFor(model => model.Fat)
        </dt>
        <dd class = "col-sm-10">
            @Html.DisplayFor(model => model.Fat)
        </dd>
        <dt class = "col-sm-2">
            @Html.DisplayNameFor(model => model.ChiPhiUocTinh)
        </dt>
        <dd class = "col-sm-10">
            @Html.DisplayFor(model => model.ChiPhiUocTinh)
        </dd>
        <dt class = "col-sm-2">
            @Html.DisplayNameFor(model => model.Chay)
        </dt>
        <dd class = "col-sm-10">
            @Html.DisplayFor(model => model.Chay)
        </dd>
        <dt class = "col-sm-2">
            @Html.DisplayNameFor(model => model.AnKeto)
        </dt>
        <dd class = "col-sm-10">
            @Html.DisplayFor(model => model.AnKeto)
        </dd>
        <dt class = "col-sm-2">
            @Html.DisplayNameFor(model => model.AnKhongGluten)
        </dt>
        <dd class = "col-sm-10">
            @Html.DisplayFor(model => model.AnKhongGluten)
        </dd>
        <dt class = "col-sm-2">
            @Html.DisplayNameFor(model => model.NguyenLieuChinh)
        </dt>
        <dd class = "col-sm-10">
            @Html.DisplayFor(model => model.NguyenLieuChinh)
        </dd>
        <dt class = "col-sm-2">
            @Html.DisplayNameFor(model => model.DinhDuongChiTiet)
        </dt>
        <dd class = "col-sm-10">
            @Html.DisplayFor(model => model.DinhDuongChiTiet)
        </dd>
        <dt class = "col-sm-2">
            @Html.DisplayNameFor(model => model.UrlHinhAnh)
        </dt>
        <dd class = "col-sm-10">
            @Html.DisplayFor(model => model.UrlHinhAnh)
        </dd>
        <dt class = "col-sm-2">
            @Html.DisplayNameFor(model => model.CachNau)
        </dt>
        <dd class = "col-sm-10">
            @Html.DisplayFor(model => model.CachNau)
        </dd>
        <dt class = "col-sm-2">
            @Html.DisplayNameFor(model => model.TrangThai)
        </dt>
        <dd class = "col-sm-10">
            @Html.DisplayFor(model => model.TrangThai)
        </dd>
        <dt class = "col-sm-2">
            @Html.DisplayNameFor(model => model.DanhMuc)
        </dt>
        <dd class = "col-sm-10">
            @Html.DisplayFor(model => model.DanhMuc.Id)
        </dd>
    </dl>
    
    <form asp-action="Delete">
        <input type="hidden" asp-for="Id" />
        <input type="submit" value="Delete" class="btn btn-danger" /> |
        <a asp-action="Index">Back to List</a>
    </form>
</div>

Views/MonAns/Details.cshtml
@model SmartCookFinal.Models.MonAn

@{
    ViewData["Title"] = "Chi tiết món ăn";
}

<!-- Bootstrap + Animate.css (chỉ thêm nếu chưa có) -->
<link rel="stylesheet" href="https://cdnjs.cloudflare.com/ajax/libs/animate.css/4.1.1/animate.min.css"/>
<link href="https://cdn.jsdelivr.net/npm/bootstrap@5.3.3/dist/css/bootstrap.min.css" rel="stylesheet" />

<div class="container mt-5">
    <div class="card shadow-lg border-0 animate__animated animate__fadeIn">
        <div class="card-header bg-success text-white d-flex justify-content-between align-items-center">
            <h3 class="mb-0">🥗 Chi Tiết Món Ăn</h3>
            <a href="@Url.Action("Index", "MonAns")" class="btn btn-light btn-sm">⬅ Quay lại danh sách</a>
        </div>

        <div class="row g-0">
            <!-- Hình ảnh món ăn -->
            <div class="col-md-5">
                <img src="@(string.IsNullOrEmpty(Model.UrlHinhAnh) ? "/images/default-food.png" : Model.UrlHinhAnh)" class="img-fluid h-100 w-100 object-fit-cover rounded-start" alt="@Model.TenMon" style="object-fit:cover; height:100%;">
            </div>

            <!-- Thông tin món ăn -->
            <div class="col-md-7">
                <div class="card-body p-4">
                    <h4 class="text-success fw-bold">@Model.TenMon</h4>
                    <p class="text-muted">@Model.MoTa</p>

                    <hr />

                    <div class="row mb-3">
                        <div class="col-6"><strong>🍽 Loại bữa ăn:</strong></div>
                        <div class="col-6 text-end"><span class="badge bg-success-subtle text-success">@Model.LoaiBuaAn</span></div>
                    </div>

                    <div class="row mb-3">
                        <div class="col-6"><strong>⏱ Thời gian nấu:</strong></div>
                        <div class="col-6 text-end">@Model.ThoiGianNau phút</div>
                    </div>

                    <div class="row mb-3">
                        <div class="col-6"><strong🔥 Lượng calo:</strong></div>
                        <div class="col-6 text-end text-danger fw-semibold">@Model.LuongCalo kcal</div>
                    </div>

                    <div class="row text-center mb-3">
                        <div class="col-4">
                            <span class="text-muted">Carbs</span><br />
                            <span class="fw-bold">@Model.Carbs g</span>
                        </div>
                        <div class="col-4">
                            <span class="text-muted">Protein</span><br />
                            <span class="fw-bold">@Model.Protein g</span>
                        </div>
                        <div class="col-4">
                            <span class="text-muted">Fat</span><br />
                            <span class="fw-bold">@Model.Fat g</span>
                        </div>
                    </div>

                    <div class="mb-3">
                        <strong>💸 Chi phí ước tính:</strong>
                        <span class="text-primary fw-bold">@Model.ChiPhiUocTinh?.ToString("N0") VND</span>
                    </div>

                    <hr />

                    <div>
                        <h5 class="text-success">📋 Cách nấu:</h5>
                        <p>@Model.CachNau</p>
                    </div>
                </div>
            </div>
        </div>
    </div>
</div>

Views/MonAns/Edit.cshtml
@model SmartCookFinal.Models.MonAn

@{
    ViewData["Title"] = "Edit";
}

<h1>Edit</h1>

<h4>MonAn</h4>
<hr />
<div class="row">
    <div class="col-md-4">
        <form asp-action="Edit">
            <div asp-validation-summary="ModelOnly" class="text-danger"></div>
            <input type="hidden" asp-for="Id" />
            <div class="form-group">
                <label asp-for="TenMon" class="control-label"></label>
                <input asp-for="TenMon" class="form-control" />
                <span asp-validation-for="TenMon" class="text-danger"></span>
            </div>
            <div class="form-group">
                <label asp-for="MoTa" class="control-label"></label>
                <input asp-for="MoTa" class="form-control" />
                <span asp-validation-for="MoTa" class="text-danger"></span>
            </div>
            <div class="form-group">
                <label asp-for="LoaiBuaAn" class="control-label"></label>
                <input asp-for="LoaiBuaAn" class="form-control" />
                <span asp-validation-for="LoaiBuaAn" class="text-danger"></span>
            </div>
            <div class="form-group">
                <label asp-for="ThoiGianNau" class="control-label"></label>
                <input asp-for="ThoiGianNau" class="form-control" />
                <span asp-validation-for="ThoiGianNau" class="text-danger"></span>
            </div>
            <div class="form-group">
                <label asp-for="LuongCalo" class="control-label"></label>
                <input asp-for="LuongCalo" class="form-control" />
                <span asp-validation-for="LuongCalo" class="text-danger"></span>
            </div>
            <div class="form-group">
                <label asp-for="Carbs" class="control-label"></label>
                <input asp-for="Carbs" class="form-control" />
                <span asp-validation-for="Carbs" class="text-danger"></span>
            </div>
            <div class="form-group">
                <label asp-for="Protein" class="control-label"></label>
                <input asp-for="Protein" class="form-control" />
                <span asp-validation-for="Protein" class="text-danger"></span>
            </div>
            <div class="form-group">
                <label asp-for="Fat" class="control-label"></label>
                <input asp-for="Fat" class="form-control" />
                <span asp-validation-for="Fat" class="text-danger"></span>
            </div>
            <div class="form-group">
                <label asp-for="ChiPhiUocTinh" class="control-label"></label>
                <input asp-for="ChiPhiUocTinh" class="form-control" />
                <span asp-validation-for="ChiPhiUocTinh" class="text-danger"></span>
            </div>
            <div class="form-group">
                <label asp-for="Chay" class="control-label"></label>
                <input asp-for="Chay" class="form-control" />
                <span asp-validation-for="Chay" class="text-danger"></span>
            </div>
            <div class="form-group">
                <label asp-for="AnKeto" class="control-label"></label>
                <input asp-for="AnKeto" class="form-control" />
                <span asp-validation-for="AnKeto" class="text-danger"></span>
            </div>
            <div class="form-group">
                <label asp-for="AnKhongGluten" class="control-label"></label>
                <input asp-for="AnKhongGluten" class="form-control" />
                <span asp-validation-for="AnKhongGluten" class="text-danger"></span>
            </div>
            <div class="form-group">
                <label asp-for="NguyenLieuChinh" class="control-label"></label>
                <input asp-for="NguyenLieuChinh" class="form-control" />
                <span asp-validation-for="NguyenLieuChinh" class="text-danger"></span>
            </div>
            <div class="form-group">
                <label asp-for="DinhDuongChiTiet" class="control-label"></label>
                <input asp-for="DinhDuongChiTiet" class="form-control" />
                <span asp-validation-for="DinhDuongChiTiet" class="text-danger"></span>
            </div>
            <div class="form-group">
                <label asp-for="UrlHinhAnh" class="control-label"></label>
                <input asp-for="UrlHinhAnh" class="form-control" />
                <span asp-validation-for="UrlHinhAnh" class="text-danger"></span>
            </div>
            <div class="form-group">
                <label asp-for="CachNau" class="control-label"></label>
                <input asp-for="CachNau" class="form-control" />
                <span asp-validation-for="CachNau" class="text-danger"></span>
            </div>
            <div class="form-group">
                <label asp-for="TrangThai" class="control-label"></label>
                <input asp-for="TrangThai" class="form-control" />
                <span asp-validation-for="TrangThai" class="text-danger"></span>
            </div>
            <div class="form-group">
                <label asp-for="DanhMucId" class="control-label"></label>
                <select asp-for="DanhMucId" class="form-control" asp-items="ViewBag.DanhMucId"></select>
                <span asp-validation-for="DanhMucId" class="text-danger"></span>
            </div>
            <div class="form-group">
                <input type="submit" value="Save" class="btn btn-primary" />
            </div>
        </form>
    </div>
</div>

<div>
    <a asp-action="Index">Back to List</a>
</div>

@section Scripts {
    @{await Html.RenderPartialAsync("_ValidationScriptsPartial");}
}